'use client';

import { useState, useRef } from 'react';
import { useRouter } from 'next/navigation';
import { Upload, FileJson } from 'lucide-react';
import { RepositoryAnalysis } from '@repolens/types';

export default function AnalyzePage() {
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  const router = useRouter();

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setLoading(true);
    setError('');

    try {
      const text = await file.text();
      const data: RepositoryAnalysis = JSON.parse(text);

      if (!data.name || !data.health) {
        throw new Error('Invalid report format. Please use a report generated by Repolens CLI.');
      }

      const reportId = Date.now().toString(36);
      sessionStorage.setItem(`report-${reportId}`, JSON.stringify(data));
      router.push(`/report/${reportId}`);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to parse report');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex flex-col">
      <nav className="border-b border-neutral-800 px-6 py-4">
        <div className="max-w-6xl mx-auto flex items-center justify-between">
          <a href="/" className="text-xl font-bold bg-gradient-to-r from-blue-500 to-purple-500 bg-clip-text text-transparent">
            RepoLens
          </a>
          <div className="flex items-center gap-6 text-sm text-neutral-400">
            <a href="/analyze" className="text-white">Analyze</a>
            <a href="/docs" className="hover:text-white transition-colors">Docs</a>
          </div>
        </div>
      </nav>

      <main className="flex-1 flex items-center justify-center px-6">
        <div className="max-w-xl w-full">
          <h1 className="text-3xl font-bold mb-2">View Report</h1>
          <p className="text-neutral-500 mb-8">Upload a JSON report generated by the Repolens CLI.</p>

          <div
            onClick={() => inputRef.current?.click()}
            className="border-2 border-dashed border-neutral-700 rounded-xl p-12 text-center cursor-pointer hover:border-blue-500/50 hover:bg-blue-500/5 transition-all"
          >
            <input
              ref={inputRef}
              type="file"
              accept=".json"
              onChange={handleFileUpload}
              className="hidden"
              disabled={loading}
            />
            {loading ? (
              <div className="text-neutral-500">Processing...</div>
            ) : (
              <>
                <FileJson className="w-12 h-12 mx-auto mb-4 text-neutral-600" />
                <div className="text-neutral-300 font-medium mb-1">Drop a JSON report here</div>
                <div className="text-sm text-neutral-600">or click to browse</div>
              </>
            )}
          </div>

          {error && (
            <div className="mt-4 p-3 bg-red-900/30 border border-red-800 rounded-lg text-red-400 text-sm">
              {error}
            </div>
          )}

          <div className="mt-8 p-4 bg-neutral-900/50 border border-neutral-800 rounded-lg">
            <h3 className="font-medium mb-2">Generate a report</h3>
            <p className="text-sm text-neutral-500 mb-3">Use the CLI to generate a JSON report:</p>
            <code className="block text-sm font-mono text-blue-400 bg-black/50 rounded p-2">
              npx repolens . --json -o report.json
            </code>
          </div>
        </div>
      </main>
    </div>
  );
}
