export default function DocsPage() {
  return (
    <div className="min-h-screen">
      <nav className="border-b border-neutral-800 px-6 py-4">
        <div className="max-w-6xl mx-auto flex items-center justify-between">
          <a href="/" className="text-xl font-bold bg-gradient-to-r from-blue-500 to-purple-500 bg-clip-text text-transparent">
            RepoLens
          </a>
          <div className="flex items-center gap-6 text-sm text-neutral-400">
            <a href="/analyze" className="hover:text-white transition-colors">Analyze</a>
            <a href="/docs" className="text-white">Docs</a>
          </div>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-4xl font-bold mb-8">Documentation</h1>

        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-4">Installation</h2>
          <pre className="bg-neutral-900 border border-neutral-800 rounded-lg p-4 text-sm font-mono overflow-x-auto">
            <code>npx repolens .</code>
          </pre>
          <p className="text-neutral-400 mt-3">Or install globally:</p>
          <pre className="bg-neutral-900 border border-neutral-800 rounded-lg p-4 text-sm font-mono overflow-x-auto mt-2">
            <code>npm install -g repolens</code>
          </pre>
        </section>

        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-4">Commands</h2>
          <div className="space-y-3">
            <div className="p-4 bg-neutral-900/50 border border-neutral-800 rounded-lg">
              <code className="text-blue-400">repolens &lt;target&gt;</code>
              <p className="text-neutral-500 text-sm mt-1">Analyze a repository (path or URL)</p>
            </div>
            <div className="p-4 bg-neutral-900/50 border border-neutral-800 rounded-lg">
              <code className="text-blue-400">repolens analyze &lt;target&gt;</code>
              <p className="text-neutral-500 text-sm mt-1">Explicit analyze command</p>
            </div>
            <div className="p-4 bg-neutral-900/50 border border-neutral-800 rounded-lg">
              <code className="text-blue-400">repolens report &lt;target&gt;</code>
              <p className="text-neutral-500 text-sm mt-1">Generate a Markdown report</p>
            </div>
            <div className="p-4 bg-neutral-900/50 border border-neutral-800 rounded-lg">
              <code className="text-blue-400">repolens compare &lt;repo1&gt; &lt;repo2&gt;</code>
              <p className="text-neutral-500 text-sm mt-1">Compare two repositories</p>
            </div>
          </div>
        </section>

        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-4">Options</h2>
          <div className="space-y-2 text-sm">
            <div className="flex gap-4"><code className="text-yellow-400 min-w-[160px]">--json</code><span className="text-neutral-500">Output as JSON</span></div>
            <div className="flex gap-4"><code className="text-yellow-400 min-w-[160px]">--markdown</code><span className="text-neutral-500">Output as Markdown</span></div>
            <div className="flex gap-4"><code className="text-yellow-400 min-w-[160px]">--html</code><span className="text-neutral-500">Output as standalone HTML</span></div>
            <div className="flex gap-4"><code className="text-yellow-400 min-w-[160px]">-o, --output &lt;path&gt;</code><span className="text-neutral-500">Write output to file</span></div>
            <div className="flex gap-4"><code className="text-yellow-400 min-w-[160px]">--no-git</code><span className="text-neutral-500">Skip Git analysis</span></div>
            <div className="flex gap-4"><code className="text-yellow-400 min-w-[160px]">--no-security</code><span className="text-neutral-500">Skip security scanning</span></div>
            <div className="flex gap-4"><code className="text-yellow-400 min-w-[160px]">--deep</code><span className="text-neutral-500">Deep analysis mode</span></div>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">Privacy</h2>
          <p className="text-neutral-400">
            RepoLens runs entirely locally. No repository data is uploaded to any server.
            The web dashboard reads reports generated by the CLI.
          </p>
        </section>
      </main>
    </div>
  );
}
